version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install sphinxcontrib-bibtex myst-parser sphinx-book-theme

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
